apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: cpu
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  redis-password: VGNuVHZFR2VrOA==